version: "3"
services:
  highload:
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - "./hload-entrypoint.sh:/app/hload-entrypoint.sh"
#      - "hload_data:/tmp/data:ro"
#      - "./db:/app/db"
#      - "./cmd:/app/cmd"
#    network_mode: host
    ports:
      - "8080:8080"
volumes:
  hload_data:
    external: true