version: "3"
services:
  highload:
    build:
      context: .
    volumes:
      - "./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf"
#      - "./db:/src/db"
#      - "./src:/src/db"
    ports:
#      - "3306:3306"
      - "8001:80"